### ISSUE TITLE
cifar10的weight decay

### ISSUE THREAD

**Issue by geyao-c** [chenyaofo/pytorch-cifar-models#11]
您好，我注意到论文中在cifar10上训练的resnet56微调时使用的weight decay是0.05，请问这是不是笔误呢。
<img width="765" alt="image" src="https://user-images.githubusercontent.com/45726681/166462684-6007532c-dbe1-41d7-a626-9ebc307029f6.png">

**Comment by chenyaofo** [comment]
请问这是什么论文？
另外本仓库也不是严格按照某篇论文进行设置的，参考的是网上比较流行的一些设置。

**Comment by chenyaofo** [comment]
因时间过久未回复，本issue关闭
