### ISSUE TITLE
accuracy score

### ISSUE THREAD

**Issue by rom954** [chenyaofo/pytorch-cifar-models#16]
I downloaded some of the networks and the accuracy is different from what you mentioned.
For example after downloading the RES-NET I checked the accuracy and it was only 0.8 (on train).
Could you please check if this is a problem  happens only to me?
(I down loaded the model from README and then uploaded into python)

**Comment by Kungbohan** [comment]
I can reproduce the results.
I guess you forget to normalize the input images?

**Comment by chenyaofo** [comment]
Reproduction can be referred at https://colab.research.google.com/github/chenyaofo/pytorch-cifar-models/blob/master/colab/start_on_colab.ipynb
