### ISSUE TITLE
Incorrect value for pretrained in the readme

### ISSUE THREAD

**Issue by brasm94** [chenyaofo/pytorch-cifar-models#3]
`model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar_resnet20", pretrained=true)`
should be 
`model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar_resnet20", pretrained="cifar10")`
or
`model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar_resnet20", pretrained="cifar100")`

**Comment by chenyaofo** [comment]
Yes. I am working to fix it.

I plan to train more models and release them recently . In the meanwhile, the api of this repo will be changed.

Thank you.

**Comment by chenyaofo** [comment]
I have corrected the readme and code.
