### ISSUE TITLE
`mobilenetv2_x0_75` trained on `Cifar100 raised HTTPError

### ISSUE THREAD

**Issue by morawi** [chenyaofo/pytorch-cifar-models#5]
All models worked (both for Cifar10 and 100); except `mobilenetv2_x0_75` trained with `Cifar100`. 

```
Downloading: "https://github.com/chenyaofo/pytorch-cifar-models/archive/master.zip" to C:\Users\xxx/.cache\torch\hub\master.zip
Downloading: "https://github.com/chenyaofo/pytorch-cifar-models/releases/download/mobilenetv2/cifar100_mobilenetv2_x0_75-9ab3e178.pt" to C:\Users\xxx/.cache\torch\hub\checkpoints\cifar100_mobilenetv2_x0_75-9ab3e178.p

...
...
 File "C:\ProgramData\Anaconda3\envs\PyTorchEight\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: Not Found
```

I thought it is the .pt filename, but looks correct to me. 

Update:
When I try to download the .pt model directly (by on [the link](https://github.com/chenyaofo/pytorch-cifar-models) to the model), it does not download and I got the message Failed-No file.
Direct download works for all the other models.

**Comment by chenyaofo** [comment]
I am sorry for late reply.

This mistake results from the wrong pretrained model url. I have fix it.
