### ISSUE TITLE
Zip file downloaded is not able to extract using all the available unzipping tools

### ISSUE THREAD

**Issue by saxenarrohit** [chenyaofo/pytorch-cifar-models#9]
url = (
            "https://rutgers.box.com/shared/static/gkw08ecs797j2et1ksmbg1w5t3idf5r5.zip"
        )

        # Streaming, so we can iterate over the response.
        r = requests.get(url, stream=True, verify=False)

state_dicts.zip file downloaded is unable to get extracted, is it because I used verify=False in request.get() command?

**Comment by chenyaofo** [comment]
Sorry, is this issue related to this repo?

**Comment by saxenarrohit** [comment]
Sorry, apologize for the mistake, yes this issue belongs to different repo, by mistake entered here since I was referring both the repos for certain concepts
